site_name: eSaudeUnB Docs

repo_name: 'fga-eps-mds/2020.1-eSaudeUnB-Wiki'
repo_url: 'https://github.com/fga-eps-mds/2020.1-eSaudeUnB-Wiki'

theme:
  name: 'material'
  language: pt
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Barlow'
  logo: assets/logo.png
  feature:
    tabs: true

nav:
  - Inicio: 
    - Home: index.md
  - Projeto:
    - Termo de Abertura do Projeto: tap.md
    - Roadmap do Produto: roadmap_produto.md
    - Plano de Gestão e Configuração de Software: gcs.md
    - Roadmap Papéis: roadmap-papeis.md
    - Estrutura Analítica do Projeto: eap.md
    - Plano de Comunicação: plano-de-comunicacao.md
    - Plano de Gerenciamento de Riscos: plano-gerenciamento-riscos.md
    - Plano de Qualidade do Projeto: plano-qualidade-projeto.md
    - Burndown de Risco: burndown_risco.md
    - Plano de Gerenciamento de Custos: plano_gerenciamento_custo.md
    - Plano de Pipeline: plano-pipeline.md
    - Testes Funcionais: test_e2e.md
    - EVM: evm.md
  - Produto:
    - Documento de Visão: DocumentoDeVisao.md
    - Documento de Arquitetura: documento_arquitetura.md
    - Backlog do Produto: backlog.md
    - Documento de Metodologia e Papeis: metodologia-e-papeis.md
    - Prototipo De Baixa Fidelidade: PrototipoDeBaixaFidelidade.md
    - Prototipo De Alta Fidelidade: prototipo_alta_fidelidade.md
    - Documento de Especificação Suplementar: DocumentoDeEspecificacaoSuplementar.md
  - Sprints:
    - Sprint 0:
      - Planejamento: planejamento_sprint0.md
      - Resultado: resultado_sprint0.md
    - Sprint 1:
      - Planejamento: planejamento_sprint01.md
      - Resultado: resultado_sprint01.md
    - Sprint 2:
      - Planejamento: planejamento_sprint2.md
      - Resultado: resultado_sprint02.md
    - Sprint 3:
      - Planejamento: planejamento_sprint03.md
      - Resultado: resultado-sprint3.md
    - Sprint 4:
      - Planejamento: planejamento_sprint04.md
      - Resultado: resultado-sprint04.md
    - Sprint 5:
      - Planejamento: planejamento_sprint05.md
      - Resultado: resultado_sprint05.md
    - Sprint 6:
      - Planejamento: planejamento_sprint06.md
      - Resultado: resultado_sprint06.md
    - Sprint 7:
      - Planejamento: planejamento_sprint07.md
      - Resultado: resultado_sprint07.md
    - Sprint 8:
      - Planejamento: planejamento_sprint08.md
      - Resultado: resultado_sprint08.md
    - Sprint 9:
      - Planejamento: planejamento_sprint9.md
      - Resultado: resultado_sprint09.md
    - Sprint 10:
      - Planejamento: planejamento_sprint10.md
      - Resultado: resultado_sprint10.md
    - Sprint 11:
      - Planejamento: planejamento_sprint11.md
      - Resultado: resultado_sprint11.md
    - Sprint 12:
      - Planejamento: planejamento_sprint12.md
      - Resultado: resultado_sprint12.md
    - Sprint 13:
      - Planejamento: planejamento_sprint13.md
      - Resultado: resultado_sprint13.md
    - Sprint 14:
      - Planejamento: planejamento_sprint14.md
      - Resultado: resultado_sprint14.md
    - Sprint 15:
      - Planejamento: planejamento_sprint15.md
      - Resultado: resultado_sprint15.md
  - Releases:
    - Release 1: release_01.md