site_name: Grupo-1 Docs

repo_name: 'fga-eps-mds/2020.1-Grupo1-Wiki'
repo_url: 'https://github.com/fga-eps-mds/2020.1-Grupo1-Wiki'

theme:
  name: 'material'
  language: pt
  palette:
    primary: 'brown'
    accent: 'brown'
  font:
    text: 'Barlow'
  icon:
    logo: material/library
  feature:
    tabs: true

nav:
  - Inicio: 
    - Home: index.md
  - Projeto:
    - Termo de Abertura do Projeto: tap.md
    - Roadmap do Produto: roadmap_produto.md
    - Plano de Gestão e Configuração de Software: gcs.md
    - Roadmap Papéis: roadmap-papeis.md
    - Estrutura Analítica do Projeto: eap.md
    - Plano de Comunicação: plano-de-comunicacao.md
    - Plano de Gerenciamento de Riscos: plano-gerenciamento-riscos.md
    - Burndown de Risco: burndown_risco.md
  - Produto:
    - Documento de Visão: DocumentoDeVisao.md
    - Backlog do Produto: backlog.md
    - Documento de Metodologia e Papeis: metodologia-e-papeis.md
    - Prototipo De Baixa Fidelidade: PrototipoDeBaixaFidelidade.md
    - Prototipo De Alta Fidelidade: prototipo_alta_fidelidade.md
    - Estrutura Analítica do Projeto: eap.md
    - Documento de Especificação Suplementar: DocumentoDeEspecificacaoSuplementar.md
  - Sprints:
    - Sprint 0:
      - Planejamento: planejamento_sprint0.md
      - Resultado: resultado_sprint0.md
    - Sprint 1:
      - Planejamento: planejamento_sprint01.md
      - Resultado: resultado_sprint01.md
    - Sprint 2:
      - Planejamento: planejamento_sprint2.md
      - Resultado: resultado_sprint02.md
    - Sprint 3:
      - Planejamento Sprint 3: planejamento_sprint03.md
